export const filmes = [
  {
    id: 1,
    titulo: "Cidade de Deus",
    diretor: "Fernando Meirelles",
    ano: 2002,
    genero: ["Drama", "Crime"],
    capa: "https://upload.wikimedia.org/wikipedia/pt/1/10/CidadedeDeus.jpg",
    emAlta: true,
    nota: 8.6,
    descricao:
      "Os caminhos de duas crianças divergem nas favelas do Rio, enquanto um se esforça para se tornar um fotógrafo e o outro um chefe do tráfico.",
  },
  {
    id: 2,
    titulo: "O Poderoso Chefão",
    diretor: "Francis Ford Coppola",
    ano: 1972,
    genero: ["Crime", "Drama"],
    capa: "https://www.europanet.com.br/upload/id_produto/107___/107366g.jpg",
    nota: 9.2,
    descricao:
      "O patriarca idoso de uma dinastia do crime organizado transfere o controle de seu império clandestino para seu filho relutante.",
  },
  {
    id: 3,
    titulo: "Interestelar",
    diretor: "Christopher Nolan",
    ano: 2014,
    genero: ["Ficção Científica", "Drama"],
    capa: "https://m.media-amazon.com/images/I/71qzTzxzoCL._AC_UF1000,1000_QL80_.jpg",
    emAlta: true,
    nota: 8.7,
    descricao:
      "Uma equipe de exploradores viaja através de um buraco de minhoca no espaço, na tentativa de garantir a sobrevivência da humanidade.",
  },
  {
    id: 4,
    titulo: "O Senhor dos Anéis: O Retorno do Rei",
    diretor: "Peter Jackson",
    ano: 2003,
    genero: ["Fantasia", "Aventura"],
    capa: "https://br.web.img2.acsta.net/medias/nmedia/18/92/91/47/20224867.jpg",
    nota: 9.0,
    descricao:
      "Gandalf e Aragorn lideram o Mundo dos Homens contra o exército de Sauron para desviar o olhar de Frodo e Sam quando eles se aproximam á Montanha da Perdição com o Um Anel.",
  },
  {
    id: 5,
    titulo: "A Origem",
    diretor: "Christopher Nolan",
    ano: 2010,
    genero: ["Ficção Científica", "Ação"],
    capa: "https://upload.wikimedia.org/wikipedia/pt/8/84/AOrigemPoster.jpg",
    nota: 8.8,
    descricao:
      "Um ladrão que rouba segredos corporativos através da tecnologia de entrar no subconsciente recebe a tarefa inversa de plantar uma idéia na mente do diretor de uma grande empresa.",
  },
  {
    id: 6,
    titulo: "Clube da Luta",
    diretor: "David Fincher",
    ano: 1999,
    genero: ["Drama"],
    capa: "https://br.web.img3.acsta.net/c_310_420/medias/nmedia/18/90/95/96/20122166.jpg",
    emAlta: true,
    nota: 8.8,
    descricao:
      "Um trabalhador de escritório e um fabricante de sabonetes formam um clube de luta clandestino que evolui para algo muito maior.",
  },
  {
    id: 7,
    titulo: "Matrix",
    diretor: "The Wachowskis",
    ano: 1999,
    genero: ["Ficção Científica", "Ação"],
    capa: "https://br.web.img3.acsta.net/medias/nmedia/18/87/12/70/19892877.jpg",
    nota: 8.7,
    descricao:
      "Um hacker aprende com os misteriosos rebeldes sobre a verdadeira natureza de sua realidade e seu papel na guerra contra seus controladores.",
  },
  {
    id: 8,
    titulo: "O Silêncio dos Inocentes",
    diretor: "Jonathan Demme",
    ano: 1991,
    genero: ["Suspense", "Crime"],
    capa: "https://cdn.fstatic.com/media/movies/covers/2016/03/o-silencio-dos-inocentes_t7031.jpg",
    emAlta: true,
    nota: 8.6,
    descricao:
      "Uma jovem deve receber a ajuda de um assassino canibal manipulador e preso para ajudar a capturar outro assassino em série, um louco que ataca suas vítimas.",
  },
  {
    id: 9,
    titulo: "Forrest Gump",
    diretor: "Robert Zemeckis",
    ano: 1994,
    genero: ["Drama", "Romance"],
    capa: "https://upload.wikimedia.org/wikipedia/pt/c/c0/ForrestGumpPoster.jpg",
    nota: 8.8,
    descricao:
      "Os governos dos presidentes Kennedy e Johnson, os eventos do Vietnã e Watergate e outras histórias são mostradas através da perspectiva de um homem do Alabama com baixo quociente intelectual.",
  },
  {
    id: 10,
    titulo: "O Fabuloso Destino de Amélie Poulain",
    diretor: "Jean-Pierre Jeunet",
    ano: 2001,
    genero: ["Comédia", "Romance"],
    capa: "https://ds0.cds.nowonline.com.br/assets/p28319_v_v8_an.jpg",
    nota: 8.3,
    descricao:
      "Amélie é uma parisiense ingênua com seu próprio senso de justiça. Ela decide ajudar as pessoas ao seu redor e, no caminho, descobre o amor.",
  },
  {
    id: 11,
    titulo: "Pulp Fiction: Tempo de Violência",
    diretor: "Quentin Tarantino",
    ano: 1994,
    genero: ["Crime", "Drama"],
    capa: "https://www.europanet.com.br/upload/id_produto/107___/107370g.jpg",
    emAlta: true,
    nota: 8.9,
    descricao:
      "As vidas de dois assassinos da máfia, um boxeador, um gângster e sua esposa, e um par de bandidos se entrelaçam em quatro histórias de violência e redenção.",
  },
  {
    id: 12,
    titulo: "A Viagem de Chihiro",
    diretor: "Hayao Miyazaki",
    ano: 2001,
    genero: ["Animação", "Aventura"],
    capa: "https://i0.wp.com/studioghibli.com.br/wp-content/uploads/2020/04/A-Viagem-de-Chihiro-DVD.jpg?fit=748%2C1074&ssl=1",
    nota: 8.6,
    descricao:
      "Uma garota é obrigada a mudar de cidade com seus pais contra a sua vontade. Durante a viagem, eles decidem pegar um atalho e se perdem, chegando a um estranho edifício, onde adentrarão um misterioso mundo de monstros e espíritos.",
  },
  {
    id: 13,
    titulo: "A Lista de Schindler",
    diretor: "Steven Spielberg",
    ano: 1993,
    genero: ["Biografia", "Drama"],
    capa: "https://upload.wikimedia.org/wikipedia/pt/1/1d/SchindlerPoster.jpg",
    nota: 9.0,
    descricao:
      "Na Polônia ocupada pelos alemães durante a Segunda Guerra Mundial, o industrial Oskar Schindler começa a ser preocupar com seus trabalhadores judeus depois de testemunhar sua perseguição pelos nazistas.",
  },
  {
    id: 14,
    titulo: "O Iluminado",
    diretor: "Stanley Kubrick",
    ano: 1980,
    genero: ["Drama", "Terror"],
    capa: "https://m.media-amazon.com/images/I/81Q+pJi4NjL._AC_UF1000,1000_QL80_.jpg",
    nota: 8.4,
    descricao:
      "Uma família se dirige a um hotel isolado para o inverno, onde uma presença sinistra influencia a violência do pai, enquanto seu filho psíquico vê presságios horríveis do passado e do futuro.",
  },
  {
    id: 15,
    titulo: "O Grande Truque",
    diretor: "Christopher Nolan",
    ano: 2006,
    genero: ["Drama", "Mistério"],
    capa: "https://static.wikia.nocookie.net/dublagempedia/images/c/cc/Grandetruque.jpg/revision/latest?cb=20201121155844&path-prefix=pt-br",
    nota: 8.5,
    descricao:
      "Depois de um trágico acidente, dois magos do palco se engajam em uma batalha para criar a ilusão final enquanto sacrificam tudo o que têm para enganar um ao outro.",
  },
  {
    id: 16,
    titulo: "Os Sete Samurais",
    diretor: "Akira Kurosawa",
    ano: 1954,
    genero: ["Ação", "Drama"],
    capa: "https://br.web.img2.acsta.net/pictures/15/07/20/20/25/180247.jpg",
    nota: 8.6,
    descricao:
      "Uma aldeia pobre sob a ameaça de bandidos recruta sete samurais para ajudá-los a se defenderem.",
  },
  {
    id: 17,
    titulo: "Amnésia",
    diretor: "Christopher Nolan",
    ano: 2000,
    genero: ["Mistério", "Thriller"],
    capa: "https://media.fstatic.com/HB8xgmitWxTKkWPIqabEgBKQwiM=/322x478/smart/filters:format(webp)/media/movies/covers/2011/09/1deef33fa858cc141e7a4f954f9c1fdd.jpg",
    nota: 8.4,
    descricao:
      "Um homem com perda da memória de curto prazo tenta investigar o homicídio da sua esposa",
  },
  {
    id: 18,
    titulo: "O Sexto Sentido",
    diretor: "M. Night Shyamalan",
    ano: 1999,
    genero: ["Drama", "Suspense"],
    capa: "https://br.web.img2.acsta.net/medias/nmedia/18/90/53/94/20101506.jpg",
    emAlta: true,
    nota: 8.2,
    descricao:
      "Um menino que consegue se comunicar com espíritos encontra ajuda de um psicólogo.",
  },
  {
    id: 19,
    titulo: "O Resgate do Soldado Ryan",
    diretor: "Steven Spielberg",
    ano: 1998,
    genero: ["Drama", "Guerra"],
    capa: "https://upload.wikimedia.org/wikipedia/pt/a/ac/Saving_Private_Ryan_poster.jpg",
    emAlta: true,
    nota: 8.6,
    descricao:
      "Depois de chegar a Normandía, um grupo de soldados precisa encontrar o único irmão vivo de três que morreram na guerra.",
  },
  {
    id: 20,
    titulo: "Titanic",
    diretor: "James Cameron",
    ano: 1997,
    genero: ["Drama", "Romance"],
    capa: "https://upload.wikimedia.org/wikipedia/pt/2/22/Titanic_poster.jpg",
    nota: 8.6,
    descricao:
      "Uma aristocrata de dezessete anos se apaixona por um artista gentil mas pobre a bordo do luxuoso e desafortunado Titanic.",
  },
  {
    id: 22,
    titulo: "Psicose",
    diretor: "Alfred Hitchcock",
    ano: 1960,
    genero: ["Terror", "Suspense"],
    capa: "https://br.web.img3.acsta.net/pictures/14/10/07/20/12/205686.jpg",
    nota: 8.5,
    descricao:
      "Uma secretária de Phoenix desvia dinheiro de um cliente de sua empresa, foge e vai a um motel remoto gerido por um jovem sob o domínio da mãe.",
  },
  {
    id: 23,
    titulo: "Taxi Driver",
    diretor: "Martin Scorsese",
    ano: 1976,
    genero: ["Drama", "Crime"],
    capa: "https://upload.wikimedia.org/wikipedia/pt/3/33/Taxi_Driver_%281976_film_poster%29.jpg",
    nota: 8.2,
    descricao:
      "Um veterano de guerra mentalmente instável trabalha à noite como taxista na cidade de Nova Iorque, onde a decadência e o desprezo alimentam seu desejo de ação violenta.",
  },
  {
    id: 24,
    titulo: "Brilho Eterno de uma Mente sem Lembranças",
    diretor: "Michel Gondry",
    ano: 2004,
    genero: ["Drama", "Romance"],
    capa: "https://br.web.img3.acsta.net/r_1280_720/img/88/89/8889818fc690422fb3785b025fe5d399.jpg",
    nota: 8.3,
    descricao:
      "Quando sua relaçao se volta complicada, um casal tenta um procedimento médico para que suas memorias sejam apagadas",
  },
];
